application: phosphor-app
version: 2
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /sounds
  static_dir: sounds
- url: /object
  static_dir: object
- url: /objects/
  script: main.py
- url: /
  script: main.py
